# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collective_order_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='collective_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Order.CollectiveOrder'),
        ),
    ]
